 const shell = require('shelljs')
 shell.exec("pwd")
shell.exec("cd /Users/ritwikgoel/Downloads && pwd && mv audio.wav ~/Documents/Projects/banana-auth/frontend")
//shell.exec("pwd")
//shell.exec()
shell.exec("meyda audio.wav zcr > outputtt.txt")